-- MySQL Script generated by MySQL Workbench
-- Sat Mar 29 12:50:00 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema closecall
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema closecall
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `closecall` DEFAULT CHARACTER SET utf8 ;
USE `closecall` ;

-- -----------------------------------------------------
-- Table `closecall`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `closecall`.`users` ;

CREATE TABLE IF NOT EXISTS `closecall`.`users` (
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `role` ENUM('PLAYER', 'HOST') NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;

USE `closecall` ;

-- -----------------------------------------------------
-- procedure findByUsername
-- -----------------------------------------------------

USE `closecall`;
DROP procedure IF EXISTS `closecall`.`findByUsername`;

DELIMITER $$
USE `closecall`$$
CREATE PROCEDURE `findByUsername` (in var_username varchar(45), in var_pass varchar(32))
BEGIN
	select `username`, `password`, `role`
    from `users`
    where `username`=var_username and `password`=var_pass;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure signup
-- -----------------------------------------------------

USE `closecall`;
DROP procedure IF EXISTS `closecall`.`signup`;

DELIMITER $$
USE `closecall`$$
CREATE PROCEDURE `signup` (in var_username varchar(45), in var_email varchar(45), in var_pass varchar(32), in var_role varchar(6))
BEGIN
	declare var_user_role ENUM('PLAYER', 'HOST');
    insert into `users`(`username`, `email`, `password`, `role`)
    values (var_username, var_email, md5(var_pass), var_role);
END$$

DELIMITER ;
SET SQL_MODE = '';
DROP USER IF EXISTS Login;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'Login' IDENTIFIED BY 'login';

GRANT EXECUTE ON procedure `closecall`.`findByUsername` TO 'Login';
GRANT EXECUTE ON procedure `closecall`.`signup` TO 'Login';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
